### PR TITLE
Setup test/release ci

### PR DESCRIPTION
**Pull request by aeongdesu**
also added `@parcel/config-default` and `@parcel/core` for build

---

these workflows have been tested
- test: https://github.com/aeongdesu/osu-bar-overlay/actions/runs/2549614656
- release(tag): https://github.com/aeongdesu/osu-bar-overlay/actions/runs/2549595117
  - result: https://github.com/aeongdesu/osu-bar-overlay/releases/tag/testtest

[Usage](https://github.com/solstice23/osu-bar-overlay#usage) should be edit because I'm not good at english

### CODE REVIEW

**Comment by solstice23** [comment]
> [Usage](https://github.com/solstice23/osu-bar-overlay#usage) should be edit because I'm not good at english

You mean making it easier to understand?

**Comment by aeongdesu** [comment]
> You mean making it easier to understand?

yes and 2 step needs to download from [releases](https://github.com/solstice23/osu-bar-overlay/releases/download/1.0/osu-bar-overlay.zip), not clone/download the repository method

and please enable releases tab in [edit repository details](https://stackoverflow.com/a/62767178)

Screenshot_20220624-121359~2

**Comment by solstice23** [comment]
Oh, i forgot that. I've updated it.

**Comment by solstice23** [comment]
Oh, i forgot that. I've updated it.

**Pull request merged**
